server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          health,
          metrics

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss}
      [%thread]
      %-5level
      [%X{traceId}]
      %logger
      - %msg%n